version: "3.1"

services:
  web:
    container_name: app
    hostname: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    
  mongo:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    ports: 
      - "27017:27017"

